### ISSUE TITLE
[DOC] Write examples for near-shell common use-cases

### ISSUE THREAD

**Issue by frol** [near/docs#155]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to do a common task from a shell and miss an example.

**Describe the solution you'd like**
I would like to have at least one example for each of the commands near-shell supports.

**Additional context**
near-shell README file (which is the only document I found) and `near-shell --help` have outdated information (e.g. `--homeDir` does not work)

**Comment by mikedotexe** [comment]
We've taken out `--homeDir` recently, but leaving this open as it relates to the issue of having examples per command.

**Comment by ashleynear** [comment]
**Acceptance Criteria:** 

As a developer building on NEAR by reading the docs,
I want to have clear examples of what each near-shell command does,
So that I have clarity on the commands I am executing as I follow the docs. 

As a developer building on NEAR by reading the docs, 
I want the examples of each near-shell command to have 
- What the help command provides for that command in shell
- What the potential failure points are that I could run into
- How to solve those failure points
So that I can easily troubleshoot and problem solve as I am following the docs

As a developer building on NEAR by reading the docs,
I want the examples for each near-shell command to be easy to find with the navigation tool,
So that I can easily find what I am looking for.

**Comment by janedegtiareva** [comment]
This issue https://github.com/near/devx/issues/203 needs to be addressed first, so that we don't do a large documentation pass that later needs to be revisited.

**Comment by thisisjoshford** [comment]
PR #516 fixes this :)
