### ISSUE TITLE
Update multi-chain relayer docs for upcoming launch

### ISSUE THREAD

**Issue by bucanero** [near/docs#1804]
Add details about manual settlement

needs further info from @ravigautham @anthony-near

**Comment by anthony-near** [comment]
Settlement is needed because the Gas Station contract is accumulating NEAR, while the paymaster accounts on foreign chains are spending native foreign chain gas tokens (ETH, BNB, SOL, etc). Manual Settlement involves several steps:
1. Withdrawing the NEAR held in the gas station contract and swapping for a token that can be bridged 
  i. may be the native gas token of the foreign chain, another token like USDC that has wide bridge support, or NEAR
2. Bridging the token from NEAR to the foreign chain 
  i. Here's an overview of bridging related to NEAR: https://knotty-marsupial-f6d.notion.site/NEAR-Bridging-Guides-f4359bd35c794dc184b098f7ed00c4ce  
3. Sending the native gas tokens to the paymaster accounts on the foreign chains
  i. A swap from the bridged token to the native gas token before sending to the paymaster accounts is necessary if the token that was bridged was not the foreign chain native gas token

**Comment by bucanero** [comment]
Settlement, paymaster, and gas fees details added in #1819
