### ISSUE TITLE
Redirect searches for primitives to the primitives pages

### ISSUE THREAD

**Issue by gagdiez** [near/docs#2002]
We have defined 6 primitives:

[Fungible Tokens (FT)](https://docs.near.org/build/primitives/ft)
[Non-Fungible Tokens (NFT)](https://docs.near.org/build/primitives/nft)
[Linkdrops](https://docs.near.org/build/primitives/linkdrop)
[Price Oracles](https://docs.near.org/build/primitives/oracles)
[Autonomous Organizations (DAO)](https://docs.near.org/build/primitives/dao)
[Decentralized Exchanges (DEX)](https://docs.near.org/build/primitives/dex)

We need to make sure that searches for them take people to the right pages
```[tasklist]
### Tasks
- [x] NFT
- [x] ft
- [x] linkdrops
- [x] price oracles
- [x] DAO
- [x] dex
```

**Comment by s-n-park** [comment]
@gagdiez , @bucanero - I've added custom rules to pin the primitive searches here:

https://dashboard.algolia.com/apps/0LUM67N2P2/rules/near

Also found a couple other top searches:
1. Gas - pinned https://docs.near.org/concepts/web3/near
2. CLI - pinned https://docs.near.org/tools/near-cli

Looks like there might be additional opportunities to improve balance and MPC searches which have avg pos of 5 ([link](https://dashboard.algolia.com/apps/0LUM67N2P2/analytics/searches/near?from=2024-03-05&to=2024-06-02)) but not sure which items we'd want to pin for this.

Lmk if you have any additional comments, otherwise will close here!
