### ISSUE TITLE
🔹[EPIC] Align BOS documentation and UI patterns

### ISSUE THREAD

**Issue by bucanero** [near/docs#2007]
### Description

As our focus has changed and BOS won't be under further development, we need to re-align our BOS/NearSocialVM documentation.

We want to document new patterns for building UIs on NEAR, and provide guidance for developers so they can select a UI solution for their dApp projects.

---

### Goal

In our documents, we need to communicate clearly that security updates for Near Social VM will no longer be available, and invite our web3 devs to move into our new UI patterns.

---

### Resources

(TBD) @mpeterdev 's team will define new UI patterns.

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/2009
- [ ] https://github.com/near/docs/issues/2051
```

**Comment by mpeterdev** [comment]
Work here can proceed before our current UI experiment is ready to present, since that will be just one option and more relevant for decentralization enthusiasts.

The primary recommended flow will revert to pre-BOS methods: developers build their frontend using a Web2 framework of their choosing, and we point them to relevant tooling necessary to interact with the protocol (i.e. near-api-js)

In the future we may have more specific recommendations per framework, like a react hooks library.

**Comment by calebjacob** [comment]
I'm hoping to add some thoughts/suggestions for the updated docs this upcoming sprint.

**Comment by bucanero** [comment]
> I'm hoping to add some thoughts/suggestions for the updated docs this upcoming sprint.

That sounds great! thanks @calebjacob 👍 Getting your feedback and suggestions would be perfect so we can provide good options to our web3 devs.

**Comment by calebjacob** [comment]
Hey @bucanero, here's my thoughts on UI documentation. Hopefully some of this is helpful! Feel free to modify or ignore as you see fit. :)

I see 3 major options that would be great to present and summarize as the first section of the UI documentation. The idea would be that the reader can quickly realize they have 3 options to choose from - each with their own set of pros/cons.

For options 1 and 2 below, I'd highly recommend pushing developers to first integrate with [Wallet Selector](https://docs.near.org/tools/wallet-selector) as their primary means of interacting with smart contracts. I've found it's the easiest way to get up and running with allowing users to connect a wallet and send signed transactions. The only use case `Wallet Selector` doesn't seem to cover is sending `view` transactions for users who haven't connected a wallet yet. So we'd need to decide on a best practice/solution for that edge case and document it.

### 1. Standard Web App

Pros:

- Build a standard web app like you normally would without any technical limitations.
- Works with any framework and combination of libraries.
- Supports SSR if using something like Next JS or Svelte Kit.
- Will have best performance overall.

Cons:

- Your web app will need to be hosted by a Web 2 hosting provider (eg: Vercel, AWS, etc).
- This means your UI layer won't be decentralized.

Summary:

Even though your UI layer won't be decentralized, your backend layer (business logic, stored data, etc) will be decentralized via smart contracts. This will be the most convenient option for most applications due to having zero technical limitations or performance impact. However, it might be a deal breaker if you require your entire stack to be decentralized.

### 2. Decentralized Hosting

This would be the solution that @mpeterdev's team will be working on. I'm not sure if we omit this option entirely for now from our public documentation or if we'd want to have a quick summary and `coming soon` tag. Michael and his team will be the best resource for refining the pros/cons and summary, but here's my rough go at it:

Pros:

- Your web app will be hosted on the blockchain allowing your entire stack to be decentralized.

Cons:

- Your options for frameworks will be limited to whatever is supported by the decentralized hosting solution.
- SSR and meta frameworks like Next JS most likely won't be supported.

Summary:

If you require your entire stack to be decentralized, this will be the best choice. However, the potential technical limitations (no SSR or meta frameworks like Next JS) are worth considering.

### 3. BOS

This will be the trickiest solution to present since we really don't want to recommend it as a valid option anymore due to security issues. The best example would be `near.social`.

Pros:

- An interesting experiment to host decentralized UI components on the blockchain.
- All components within the community can be imported/forked.

Cons:

- Extremely limited due to proprietary React syntax and security concerns.
- Unable to use libraries from NPM.
- Unsupported moving forward due to security issues.

Summary:

The BOS VM was an interesting experiment that ultimately had too many security issues and technical limitations to be considered a valid option for building robust web apps moving forward.
