### ISSUE TITLE
how-to-write-contracts-that-talk-to-each-other needs rework to remove studio

### ISSUE THREAD

**Issue by janedegtiareva** [near/docs#273]
This tutorial relies heavily on studio, and we need to rework it to align with the move to gitpod.

**Comment by amgando** [comment]
this is the related docs page: https://docs.near.org/docs/tutorials/how-to-write-contracts-that-talk-to-each-other

**Comment by amgando** [comment]
start by cloning this repo: https://github.com/near-examples/token-contract-as

**Comment by potatodepaulo** [comment]
In order to accomplish this:
* [ ] Read through the existing tutorial to understand the desired end result.
* [ ] Remove all instances of "NEAR studio" and replace them with generic IDE references or references to GitPod.
* [ ] Change the flow to rely on the example linked above, which can also be seen [here](https://examples.near.org/token-contract-as)
* [ ] Complete the tutorial without NEAR Studio by copying and pasting the example code.
