### ISSUE TITLE
[BUG] Docs still talk about state rent

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#345]
**Describe the bug**
This page https://docs.near.org/docs/concepts/gas still has "state rent".

**Expected behavior**
Should be:
 - Called differently, as it's not only about gas 
 - Describe storage pricing (details are in "Storage" section of https://near.org/blog/near-protocol-economics/)

**Screenshots**
![photo_2020-05-18 17 28 38](https://user-images.githubusercontent.com/175486/82271583-08e49e80-992d-11ea-8a9e-100be4f138e0.jpeg)

**:pencil: Location**
https://docs.near.org/docs/concepts/gas

**Comment by amgando** [comment]
#373 was merged and closes this

**Comment by firatNEAR** [comment]
I am re-opening this issue since there are multiple places in Docs which still state `state rent`
* https://docs.near.org/integrator/faq#is-there-a-minimum-account-balance
* https://nomicon.io/RuntimeSpec/Scenarios/FinancialTransaction#processing-receipt
* https://near.org/papers/economics-in-sharded-blockchain/#transaction-and-storage-fees (Not sure if this document relates to this near/docs

**Comment by thisisjoshford** [comment]
#1245 Fixes this issue
