### ISSUE TITLE
[GUIDE] near-shell

### ISSUE THREAD

**Issue by amgando** [near/docs#367]
we could use a comprehensive guide for NEAR Shell that includes content like this

https://github.com/near-examples/workshop--exploring-assemblyscript-contracts/tree/master/assembly/A.sample-projects/01.greeting#integration-tests-with-near-shell

**Comment by AnaisUrlichs** [comment]
@amgando @ashleynear I would be happy to take this over; @ashleynear could you fill me in if you and Jane already worked on it and if there is something that I should know about? Otherwise, I could create a draft and run it by some developer in the community to get feedback. Please let me know what you think

**Comment by ashleynear** [comment]
@AnaisUrlichs we did not :)

**Comment by thisisjoshford** [comment]
Issues completed, closing this epic :)
