### ISSUE TITLE
Create user stories for EVM use cases

### ISSUE THREAD

**Issue by artob** [near/docs#560]
As discussed today with @ilblackdragon, let's create user stories for EVM use cases.

https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

**Comment by djsatok** [comment]
# End-user with Ethereum experience

*Overview*. A user of a dApp would like to keep working with the dApp after its' migration to NEAR.

## Job stories (from the user point of view)

1. When I start using NEAR, I want to be guided so I can understand what changes in the operations
2. When I start using NEAR, I want to have quick and straightforward setup so I can easily continue my usage of the dApp.
3. When I start using NEAR, I want to stay in the same interfaces that I used to use so I can feel comfortable
4. When I start using NEAR, I want to have clear separation of the chains to which I send transactions so I can control the destination of the transactions
5. If I'm using multiple dApps, I want their NEAR parts to be either interoperable with Ethereum or have clear differences so I won't expect the outcomes of one dApp working on NEAR to be used as inputs to the other dApp on Ethereum
6. When I use NEAR, I want to have an ability to use Ethereum tokens so I can a) fund operations on NEAR b) pay for dApp services c) use it as a collateral/similar within dApp
7. After I've figured out the benefits of NEAR, I want to be able to take full control of my operations on NEAR so I feel more secure


## Architect

**Comment by djsatok** [comment]
# WIP: dApp developer with Ethereum experience

**Overview**. A developer of a dApp would like to migrate his operations to NEAR completely or provide NEAR as an option of the destination chain.

## Job stories (from the developer point of view)

1. When I explore NEAR, I want to get fast and clear answers how to solve my problems so I can easily assess the chain proposition
2. When I start working with NEAR, I want to get clear directions how to migrate my existing codebase so I can bootstrap the operations easily
3. When I start working with NEAR, I want to get $NEAR easily so I can fund my operations
4. When I start working with NEAR, I want to have clear guidelines (tech, legal, UI, tutorials, etc.) how to move my users from Ethereum to NEAR so I don't spend my time and resource into solving this. The guidelines should focus on minimising the necessary steps for the user so I don't confuse and loose my user base.
5. When I develop for NEAR, I want my ordinary tools work with NEAR chain with minimum additional moves so I can keep the development approaches that I use and not spending additional time for education / switching the context


## Guidelines based on the job stories

**Comment by djsatok** [comment]
# WIP: NEAR end-user

**Overview**. An existing NEAR user would like to work with the EVM dApp.

## Job stories (from the user point of view)

1. 

## Guidelines based on the job stories

1.

**Comment by djsatok** [comment]
# WIP: NEAR developer, access to EVM user base

**Overview**. A developer of a NEAR-native dApp would like to support users that came to NEAR ecosystem form migrated Ethereum apps.

## Job stories (from the developer point of view)

1. When I develop a smart contract, I don't want to think about the user-native runtime (develop multiple contracts within different runtimes OR different interfaces for the same contract, for example), since I expect this to be sorted out by the protocol
2. When I develop front-end for the dApp, I would prefer not to think about the user-native runtime (similar to the smart contracts), so I do not change anything in my app.
3. In case the previous point is is not the case, I would like to have a single JS library with **EVM supported** and **not supported by EVM accounts** marked methods. I expect to be able to implement any logic using EVM supported methods only (probably, more simple UX can be implemented with the usage of methods that are not supported by EVM-native accounts). I expect the library to take care about runtime differences as much as possible. All of these devoted to simplify my development and maintenance process.

## Guidelines
1. EVM accounts should be able to schedule calls to NEAR contracts (1)
2. From the contract point of view there should not be any difference between EVM-account or NEAR-native account call; or the differences should be handled in the runtime
3. [`near-api-js`](https://github.com/near/near-api-js/) should be extended to EVM-accounts at least within these sections:
  a. User log in with Metamask
  b. Status of the used user account (NEAR native or EVM)
  c. Preparation of transactions for signing (to be send to Metamask)
  d. Interaction with relayers of Metamask messages
  e. Support of extension of the EVM account to full NEAR account (transaction history, deployed contracts, balances of the tokens, etc.)

**Comment by djsatok** [comment]
@artob should we close this?
