### ISSUE TITLE
[BUG] Update the references to mainnet genesis file after a recent refactoring to nearcore

### ISSUE THREAD

**Issue by frol** [near/docs#719]
![image](https://user-images.githubusercontent.com/304265/119496236-abeaa800-bd39-11eb-83ad-da945100a631.png)

After this PR https://github.com/near/nearcore/pull/4292, the folder should be `nearcore/res/`

**Comment by thisisjoshford** [comment]
@frol Before I saw this issue just now, I noticed some broken links due to this refactor and started fixing them here ( https://github.com/near/docs/pull/728
& https://github.com/near/docs/pull/726 ). The solution I implemented was to tell people how to query this data via the `protocol_config` endpoint rather than linking to the config file directly. Should I continue on this path for the remaining links above in `gas.MD` or direct link to the new location? My thoughts are that if things get refactored or updated again the RPC endpoint will show the most current data and will minimize doc maintenance.

**Comment by frol** [comment]
@thisisjoshford yeah, using the `protocol_config` endpoint is even better! Thanks for pointing it out! I just used grep to find the broken links, and did not really dig into the reason why those links are used in the first place. Thanks for pointing that out! Should we close this issue?
